obstacles:
  - name: "obstacle_1"
    position: [4.0, -1.0, 5.0]  # (x, y, z)
    radius: 0.2  # 半径
    is_dynamic: false # 静态障碍物
  - name: "obstacle_2"
    position: [6.0, 1.0, 5.0]
    radius: 0.3 
    is_dynamic: false # 静态障碍物
  - name: "obstacle_3"
    position: [8.0, -2.0, 5.0]
    velocity: [-0.05, 0.0, 0.0]
    radius: 0.25 # 动态障碍物
    is_dynamic: true # 动态障碍物